### ISSUE TITLE
hi, the data link is not available, please check and update it, thank you for you job

### ISSUE THREAD

**Issue by zengxia** [RomeroBarata/skeleton_based_anomaly_detection#1]

**Comment by RomeroBarata** [comment]
Hi @zengxia,
I tried the link and it seems to be working fine here. Can you please give me more details of what you see when you click on it? Note that by clicking on the data.zip file you only get a partial view of the files, to have access to all files you must download the whole data.zip file. Thanks!

**Comment by zengxia** [comment]
oh, i tried again, this time it works, amazing... the link returned a 404 code before.

**Comment by zengxia** [comment]
Sorry, I still feel so confused about how to run the visualise module, cause there are so many arguments and i can't find the videos in the data you provide also.

**Comment by RomeroBarata** [comment]
Hi @zengxia,
For visualisation you need the frames of the videos, which you can find by downloading the original data set. To visualise the reconstructed/predicted skeletons, you need to save them. You can do that by adding the --write_predictions flag to combined_model (it will write to the directory of the pre-trained model).

**Comment by musicshmily** [comment]
作者您好 ，感谢您的工作，能够给一些相关的命令说明呢

**Comment by musicshmily** [comment]
> 您好@zengxia，
> 对于可视化，您需要视频的帧，您可以通过下载原始数据集找到它们。要想象重建/预测的骨架，您需要保存它们。您可以通过将--write_predictions标志添加到combined_model（它将写入预先训练的模型的目录）来实现。

作者您好，感谢您的工作，能够给一些相关的命令说明呢
