### ISSUE TITLE
Dear sir: what does the data mean in the skeleton_based_anomaly_detection\data\HR-ShanghaiTech\training\trajectories\00\01_001 file

### ISSUE THREAD

**Issue by algorithmlixuan** [RomeroBarata/skeleton_based_anomaly_detection#10]
hello, thanks for the great work, could you tell me what does the data mean in the skeleton_based_anomaly_detection\data\HR-ShanghaiTech\training\trajectories\00\01_001 file?
I'am afraid I can't figure out what data you use to train the network, would you like to tell me that?
![image](https://user-images.githubusercontent.com/30352320/67469957-90ac4800-f67f-11e9-9ead-405f47a5648f.png)

**Comment by algorithmlixuan** [comment]
> In general, the order of folders/files is sceneId -> videoId -> personId.csv file. In the personId.csv file, the first column is the frame id, the 2~35 columns are xy-coordinates location. And the 00 folder is not the sceneId, it looks like include all the video.

thank you very much I understand now, if you are also working on this project, could we add  contact like wechat and have a communication?

**Comment by RomeroBarata** [comment]
Hi @algorithmlixuan,

@Cambrainnnnn answer is correct!

Kind regards,
Romero

**Comment by Cambrainnnnn** [comment]
@algorithmlixuan QQ：401105480
