### ISSUE TITLE
Dear sir,I have some questions for the function _from_image_to_global

### ISSUE THREAD

**Issue by algorithmlixuan** [RomeroBarata/skeleton_based_anomaly_detection#12]
hello , thanks for the great work. I have some questions for the  function _from_image_to_global, could you tell me the principle in the function?, why can pixel coordinates divided by the video_resolution be the global coordinates? thank you very much.
![image](https://user-images.githubusercontent.com/30352320/68528733-a5503780-0331-11ea-8aa7-01fdcf2059bc.png)

**Comment by RomeroBarata** [comment]
Hi @algorithmlixuan,

The name of the function is a bit confusing, sorry for that. We can consider these coordinates to still be in pixel coordinates, but now they range from 0 to 1.

**Comment by algorithmlixuan** [comment]
@RomeroBarata  I understand now. thank you very much
