### ISSUE TITLE
Question regarding the "different" trained models

### ISSUE THREAD

**Issue by mayaghaei** [RomeroBarata/skeleton_based_anomaly_detection#19]
Hi Romero,

I have a curiosity regarding the "various" pre-trained models for different scenes captured with different cameras in ShanghaiTech dataset that you provided. I was trying to do some cross dataset tests and I realized that models inside different folders (from 1 to 12), they are all exactly the same models. Prior to this I thought you are actually training one model per camera. 

Can you please explain this a little further? I cannot get my head around the reason for it. Do these models suppose to be different or they should be actually the same thing?

Thanks again :)

**Comment by RomeroBarata** [comment]
Hi @mayaghaei,

The code is set up in a more flexible way to do per-camera train/test, but the pre-trained models inside folders 1-12 are indeed the same and were trained on training data from cameras 1-12. The reason we do that is to follow the experimental procedure of previous works on the ShanghaiTech dataset, as mentioned in Section 4.1.1 of the paper.

A per-camera model is more desirable but you get less training data and it might fail if the testing camera moves position, which happens in the ShanghaiTech dataset (e.g. camera 7). A single model is more robust to these sort of problems.

Kind regards,
Romero

**Comment by mayaghaei** [comment]
Thank you @RomeroBarata , all clear!
