### ISSUE TITLE
Questions about csv file and online inference

### ISSUE THREAD

**Issue by Cambrainnnnn** [RomeroBarata/skeleton_based_anomaly_detection#2]
Hi, thanks for your inspiring work. I have few questions:
How do i get the csv file of skeleton trajectories of all person? need to implementing the Hungarian algorithm?
How do i make the online inference?
looking forward to your reply

**Comment by RomeroBarata** [comment]
Hi @Cambrainnnnn,
I've provided the .csv files for training and testing. The link for download is in the project README.
I didn't implement code for online inference since all skeleton data were extracted before hand, and this suited my research purposes.
