### ISSUE TITLE
Questions about labels 

### ISSUE THREAD

**Issue by usamahjundia** [RomeroBarata/skeleton_based_anomaly_detection#22]
Hello romero. First of all, thank you for the amazing work!

Recently, i tried porting the whole pipeline to be suitable for use for real-time detection. In order to test my port, i also implemented some "Fake" stream to visualize the skeletons, to visualize when does an anomaly happen (by the help of the GT anomaly mask) and for each timestep accumulate skeletons for each IDs to count the reconstruction score.

What i want to know, do you have labels for which GT entity / trajectory is causing the frame to be anomallous?

I tested on ShanghaiTech test dataset, video 0014 under folder 01, and on the anomalous frames, there are 2 entities i thought would cause the anomaly but can not decide which is the one causing anomaly because i dont have info on GT trajectory-level label

**Comment by RomeroBarata** [comment]
Hi @usamahjundia,

I don't have entity-level anomaly mask but the original dataset comes with pixel-level mask, which you could use to check the anomalies similarly.

Kind regards,
Romero

**Comment by usamahjundia** [comment]
thanks! i should've read more thoroughly next time.
