### ISSUE TITLE
Question: How many skeleton joints as input in your paper/network/code?

### ISSUE THREAD

**Issue by barondra** [RomeroBarata/skeleton_based_anomaly_detection#25]
Hi @RomeroBarata,

Thank you for sharing in Github. Excellent paper! I want to use your network and train on different dataset and then I can compare results. Is this code plug and play? How many skeleton joints as input? Which skeleton format should I follow? Is your code adapted to number of skeleton joints? Please kindly deliberate your answer.

Best regards

**Comment by RomeroBarata** [comment]
Hi @barondra,

Thanks for your interest in our work. You should be able to train your own models if you have the skeleton data. We represent a skeleton with 17 joints (34-dimensional input) and you can check the format by downloading some of the provided data. The data are .csv files, one per person trajectory, containing the coordinates of the person in the scene in each frame. I can't recall if the code works with other number of joints, I believe it should and if not it is just some small modification to make in it.

Kind regards,
Romero

**Comment by barondra** [comment]
Yes, thank you very much for your reply!
Again your work has been much inspiration to people who are interested in video anomaly detection. I will definitely give a reference.

**Comment by barondra** [comment]
The data is represented as 17 joints, but after I download the data from your link and open the .csv files, there are 35 columns in every row instead of 34. What is the meaning of the extra column?

**Comment by barondra** [comment]
https://github.com/RomeroBarata/skeleton_based_anomaly_detection/issues/10#issuecomment-545846114
Ah yes, I have seen this but just forgotten. The first (extra) column is the frame number. Nevermind please.
