### ISSUE TITLE
dataset download issue

### ISSUE THREAD

**Issue by NagasadaSanshiro** [RomeroBarata/skeleton_based_anomaly_detection#27]
Hi
I click the following link https://bit.ly/2WGHz56  but seems I cannot get access to it, and I visit the shanghaitech website, in where the onedrive link doesn't work either. 
Can you please tell me how to obtain the dataset? 

best regards,

**Comment by RomeroBarata** [comment]
Hi NagasadaSanshiro,

I updated the link and it should work again now. Please let me know if you have any other issues downloading the data.

Kind regards,
Romero
