### ISSUE TITLE
Skeleton detection model

### ISSUE THREAD

**Issue by chamecall** [RomeroBarata/skeleton_based_anomaly_detection#33]
Hello there!
Thanks for your work!
Can you tell what skeleton detection model did you use for generation of your masks?

**Comment by RomeroBarata** [comment]
Hi,

I used [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose) for skeleton detection. Is that what you mean by mask?

Kind regards,
Romero

**Comment by chamecall** [comment]
> Hi,
> 
> I used [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose) for skeleton detection. Is that what you mean by mask?
> 
> Kind regards, Romero

yes, that's it.
many thanks
