### ISSUE TITLE
Skeleton trajectory dataset

### ISSUE THREAD

**Issue by aytek03** [RomeroBarata/skeleton_based_anomaly_detection#36]

**Comment by aytek03** [comment]
Hi @RomeroBarata 

You use 34 joint points (17 x, y coordinates) but in alphaPose, they use MSCOCO keypoint dataset and it has 18 joint x,y joints.

Which joint coordinate did you not use?

Thanks

**Comment by RomeroBarata** [comment]
Hi @aytek03,

AlphaPose has two format options. You can see their specification [here](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/output.md#keypoint-ordering).

Kind regards,
Romero

**Comment by aytek03** [comment]
Hi @RomeroBarata 

I missed that point.

Thanks,
