### ISSUE TITLE
the issue of visualisation.py

### ISSUE THREAD

**Issue by Nano0073** [RomeroBarata/skeleton_based_anomaly_detection#8]
How to perform real-time anomaly detection?
Can I use a computer to connect to a USB camera for real-time anomaly detection?
Is it using  visualisation.py?
I am a newcomer to deep learning and I am very interested in your research. I hope that you can take the time to answer my questions. Thank you.

**Comment by RomeroBarata** [comment]
Hi @Nano0073,
Unfortunately the code doesn't support real-time anomaly detection. The `visualisation.py` file is mostly to generate some useful plots of the output generated by a pre-trained network (e.g. how does the predicted skeletons look like, etc.).
