### ISSUE TITLE
How to generate frame level prediction mask from pixel level mask?

### ISSUE THREAD

**Issue by AshviniKSharma** [RomeroBarata/skeleton_based_anomaly_detection#9]
Hello, Thank you for your excellent work. I want to know is there any way to generate  frame-level anomaly mask from pixel-level anomaly mask of predictions. I tried doing max over all values, but it's creating a lot of false outcomes. Can you help?

**Comment by RomeroBarata** [comment]
Hi @AshviniKSharma ,
A frame-level anomaly means that at least one pixel in the frame is anomalous. So, from the pixel-level mask, if you identify at least one anomalous pixel, you can set the frame-level mask to one.

**Comment by Cambrainnnnn** [comment]
Hi @AshviniKSharma 
I want to know which file or function could get the pixel-level anomaly mask? I just set the anomaly result if the frame anomaly score out the threshold.
Thanks~
